### ISSUE TITLE
iamklaus/nextcloud server not starting site can’t be reached

### ISSUE THREAD

**Issue by almgwary** [iamklaus/nextcloud#15]
### Description:
iamklaus/nextcloud server not starting, 

> This site can’t be reached

### Logs
```
crond: wakeup dt=10
crond: wakeup dt=50
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  line php -f /var/www/html/occ face:background_job -t 900
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  line php -f /var/www/html/occ face:background_job -t 900
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  line php -f /var/www/html/occ face:background_job -t 900
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  line php -f /var/www/html/occ face:background_job -t 900
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  job: 0 php -f /var/www/html/cron.php
crond:  line php -f /var/www/html/occ face:background_job -t 900
crond: child running /bin/bash
crond: USER www-data pid  77 cmd php -f /var/www/html/cron.php
Exception: Not installed in /var/www/html/lib/base.php:282

Stack trace:
#0 /var/www/html/lib/base.php(663): OC::checkInstalled(Object(OC\SystemConfig))
#1 /var/www/html/lib/base.php(1104): OC::init()
#2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')

}
crond: wakeup dt=10
crond: wakeup dt=50
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  line php -f /var/www/html/occ face:background_job -t 900
```

## Portainer stack

```
version: '2'

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /var/lib/docker/volumes/Nextcloud_Database5:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: iamklaus/nextcloud:fpm
    restart: always
    ports:
      - 8080:80
      - 8083:443
    links:
      - db
    volumes:
      - /var/lib/docker/volumes/Nextcloud_Application5:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=1G
```
